version: '3.9'
services:
  mysql:
    container_name: mysql
    image: mysql:5.7
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: "devops"
      MYSQL_ROOT_PASSWORD: "demo@123"
    volumes:
      - vol_latest:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - netlatest

  flaskapp:
    image: chaudharipankaj/twotierapp:v1
    ports:
      - "5000:5000"
    environment:
      MYSQL_HOST: "mysql"
      MYSQL_USER: "root"
      MYSQL_PASSWORD: "demo@123"
      MYSQL_DB: "devops"
    depends_on:
      mysql:
        condition: service_healthy
    networks:
      - netlatest

volumes:
  vol_latest:

networks:
  netlatest:
